name: Preview script outputs

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Test Sidebar Script
        run: |
            bash helper-scripts/gen-subxml.sh
            echo "Outputting Sidebar XML..."
            cat sidebar.xml
      - name: Test MD File generation 
        run: bash helper-scripts/gen-md.sh